---
- name: Ensure PHPMyAdmin is installed.
  yum: pkg=phpmyadmin state=installed enablerepo=epel
  notify: restart apache

- name: Add default username and password for MySQL connection.
  lineinfile: >
    dest=/etc/phpMyAdmin/config.inc.php
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
  - { key: host, value: "{{ phpmyadmin_mysql_host }}" }
  - { key: port, value: "{{ phpmyadmin_mysql_port }}" }
  - { key: socket, value: "{{ phpmyadmin_mysql_socket }}" }
  - { key: connect_type, value: "{{ phpmyadmin_mysql_connect_type }}" }
  - { key: user, value: "{{ phpmyadmin_mysql_user }}" }
  - { key: password, value: "{{ phpmyadmin_mysql_password }}"}
