---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define phpmyadmin_config_file.
  set_fact:
    phpmyadmin_config_file: "{{ __phpmyadmin_config_file }}"
  when: phpmyadmin_config_file is not defined

# Setup/install tasks.
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Add default username and password for MySQL connection.
  lineinfile: >
    dest={{ phpmyadmin_config_file }}
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
  with_items:
    - key: host
      value: "{{ phpmyadmin_mysql_host }}"
    - key: port
      value: "{{ phpmyadmin_mysql_port }}"
    - key: socket
      value: "{{ phpmyadmin_mysql_socket }}"
    - key: connect_type
      value: "{{ phpmyadmin_mysql_connect_type }}"
    - key: user
      value: "{{ phpmyadmin_mysql_user }}"
    - key: password
      value: "{{ phpmyadmin_mysql_password }}"
