---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enablerepo: "remi,remi-php70"
    phpmyadmin_enablerepo: "remi,remi-php70"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

    - name: Set php_packages for PHP 7.0 Debian 8 install.
      set_fact:
        php_packages:
          - php7.0-common
          - php7.0-cli
          - php7.0-dev
          - php7.0-fpm
          - libpcre3-dev
          - php7.0-opcache
          - php7.0-apcu
      when: ansible_distribution == 'Debian'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.repo-dotdeb
      when: ansible_distribution == 'Debian'
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.phpmyadmin

  post_tasks:
    - name: Ensure phpMyAdmin is running.
      uri:
        url: "http://127.0.0.1/phpmyadmin/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
