---
- name: Converge
  hosts: all
  become: true

  vars:
    phpmyadmin_enablerepo: "remi,remi-php72"

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: geerlingguy.repo-remi
      when: ansible_os_family == 'RedHat'
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php-versions
    - role: geerlingguy.php
    - role: geerlingguy.php-mysql
    - role: geerlingguy.phpmyadmin

  post_tasks:
    - name: Ensure phpMyAdmin is running.
      uri:
        url: "http://127.0.0.1/phpmyadmin/"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 60
      delay: 1
